<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-08T15:08:32 IST" name="Suite" finished-at="2022-06-08T15:09:40 IST" duration-ms="68090">
    <groups>
    </groups>
    <test started-at="2022-06-08T15:08:32 IST" name="Test" finished-at="2022-06-08T15:09:40 IST" duration-ms="68090">
      <class name="testsuite2.test.EntityType_PUT_with_indistinct">
        <test-method signature="Update_EntityType(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_PUT_with_indistinct@5c5eefef]" started-at="2022-06-08T15:08:32 IST" name="Update_EntityType" data-provider="ProbaseURL" finished-at="2022-06-08T15:08:58 IST" duration-ms="25945" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at auth.api.VerifyStatusLine.ensureLine200(VerifyStatusLine.java:22)
at depend_1.api.FrameSuite.EntityType_PUT_Update(FrameSuite.java:4570)
at main.api.ExecuteAPILead.Put(ExecuteAPILead.java:181)
at apache.api.Shuffle.globalAdmin(Shuffle.java:70)
at apache.api.Operation.worksheet(Operation.java:13)
at testsuite2.test.EntityType_PUT_with_indistinct.Update_EntityType(EntityType_PUT_with_indistinct.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Update_EntityType -->
      </class> <!-- testsuite2.test.EntityType_PUT_with_indistinct -->
      <class name="scenarios.api.EntityType">
        <test-method signature="filename()[pri:0, instance:scenarios.api.EntityType@4a94ee4]" started-at="2022-06-08T15:08:32 IST" name="filename" finished-at="2022-06-08T15:08:32 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- filename -->
      </class> <!-- scenarios.api.EntityType -->
      <class name="testsuite2.test.EntityType_DELETE_with_distinct_EntityTypeID">
        <test-method signature="Delete_Specific_EntityType_using_EntityTypeID(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_DELETE_with_distinct_EntityTypeID@72d1ad2e]" started-at="2022-06-08T15:09:18 IST" name="Delete_Specific_EntityType_using_EntityTypeID" data-provider="ProbaseURL" finished-at="2022-06-08T15:09:34 IST" duration-ms="16146" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HTTP/1.1 200 OK] but found [HTTP/1.1 404 Not Found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 404 Not Found]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at auth.api.VerifyStatusLine.ensureLine200(VerifyStatusLine.java:22)
at depend_1.api.FrameSuite.EntityType_DELETE_Delete(FrameSuite.java:4712)
at main.api.ExecuteAPILead.Delete(ExecuteAPILead.java:235)
at apache.api.Shuffle.globalAdmin(Shuffle.java:73)
at apache.api.Operation.worksheet(Operation.java:13)
at testsuite2.test.EntityType_DELETE_with_distinct_EntityTypeID.Delete_Specific_EntityType_using_EntityTypeID(EntityType_DELETE_with_distinct_EntityTypeID.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Delete_Specific_EntityType_using_EntityTypeID -->
      </class> <!-- testsuite2.test.EntityType_DELETE_with_distinct_EntityTypeID -->
      <class name="scenarios.api.EntityType_EntityTypeID">
        <test-method signature="filename()[pri:0, instance:scenarios.api.EntityType_EntityTypeID@595b007d]" started-at="2022-06-08T15:09:18 IST" name="filename" finished-at="2022-06-08T15:09:18 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- filename -->
      </class> <!-- scenarios.api.EntityType_EntityTypeID -->
      <class name="testsuite2.test.EntityType_POST_with_indistinct">
        <test-method signature="Create_EntityType(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_POST_with_indistinct@16293aa2]" started-at="2022-06-08T15:08:58 IST" name="Create_EntityType" data-provider="ProbaseURL" finished-at="2022-06-08T15:09:12 IST" duration-ms="14485" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create_EntityType -->
      </class> <!-- testsuite2.test.EntityType_POST_with_indistinct -->
      <class name="extend.api.CreateReport">
        <test-method signature="extend()[pri:1, instance:extend.api.CreateReport@222545dc]" started-at="2022-06-08T15:08:32 IST" name="extend" finished-at="2022-06-08T15:08:32 IST" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extend -->
      </class> <!-- extend.api.CreateReport -->
      <class name="testsuite2.test.EntityType_GET_with_distinct_EntityTypeID">
        <test-method signature="View_Specific_EntityType_using_EntityTypeID(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_GET_with_distinct_EntityTypeID@38c6f217]" started-at="2022-06-08T15:09:34 IST" name="View_Specific_EntityType_using_EntityTypeID" data-provider="ProbaseURL" finished-at="2022-06-08T15:09:40 IST" duration-ms="5279" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at auth.api.VerifyStatusLine.ensureLine200(VerifyStatusLine.java:22)
at depend_1.api.FrameSuite.EntityType_GET_View_Specific_EntityType(FrameSuite.java:4606)
at main.api.ExecuteAPILead.View_ID(ExecuteAPILead.java:301)
at apache.api.Shuffle.globalAdmin(Shuffle.java:67)
at apache.api.Operation.worksheet(Operation.java:13)
at testsuite2.test.EntityType_GET_with_distinct_EntityTypeID.View_Specific_EntityType_using_EntityTypeID(EntityType_GET_with_distinct_EntityTypeID.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- View_Specific_EntityType_using_EntityTypeID -->
      </class> <!-- testsuite2.test.EntityType_GET_with_distinct_EntityTypeID -->
      <class name="testsuite2.test.EntityType_GET_with_indistinct">
        <test-method signature="View_EntityType(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_GET_with_indistinct@5158b42f]" started-at="2022-06-08T15:09:12 IST" name="View_EntityType" data-provider="ProbaseURL" finished-at="2022-06-08T15:09:18 IST" duration-ms="5812" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- View_EntityType -->
      </class> <!-- testsuite2.test.EntityType_GET_with_indistinct -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
