<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-09T19:10:11 IST" name="Suite" finished-at="2022-06-09T19:10:37 IST" duration-ms="25973">
    <groups>
    </groups>
    <test started-at="2022-06-09T19:10:11 IST" name="Test" finished-at="2022-06-09T19:10:37 IST" duration-ms="25973">
      <class name="testsuite2.test.EntityType_PUT_with_indistinct">
        <test-method signature="Update_EntityType(java.lang.String)[pri:0, instance:testsuite2.test.EntityType_PUT_with_indistinct@6b81ce95]" started-at="2022-06-09T19:10:11 IST" name="Update_EntityType" data-provider="ProbaseURL" finished-at="2022-06-09T19:10:37 IST" duration-ms="25623" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://lnmjapi.adappt.ai/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at auth.api.VerifyStatusLine.ensureLine200(VerifyStatusLine.java:22)
at depend_1.api.FrameSuite.EntityType_PUT_Update(FrameSuite.java:4570)
at main.api.ExecuteAPILead.Put(ExecuteAPILead.java:181)
at apache.api.Shuffle.globalAdmin(Shuffle.java:70)
at apache.api.Operation.worksheet(Operation.java:13)
at testsuite2.test.EntityType_PUT_with_indistinct.Update_EntityType(EntityType_PUT_with_indistinct.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Update_EntityType -->
      </class> <!-- testsuite2.test.EntityType_PUT_with_indistinct -->
      <class name="scenarios.api.EntityType">
        <test-method signature="filename()[pri:0, instance:scenarios.api.EntityType@359f7cdf]" started-at="2022-06-09T19:10:11 IST" name="filename" finished-at="2022-06-09T19:10:11 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- filename -->
      </class> <!-- scenarios.api.EntityType -->
      <class name="extend.api.CreateReport">
        <test-method signature="extend()[pri:1, instance:extend.api.CreateReport@6572421]" started-at="2022-06-09T19:10:11 IST" name="extend" finished-at="2022-06-09T19:10:11 IST" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extend -->
      </class> <!-- extend.api.CreateReport -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
