<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lokesh-PC" failures="1" tests="3" name="Test" time="25.973" errors="0" timestamp="2022-06-09T19:10:37 IST">
  <testcase classname="scenarios.api.EntityType" name="filename" time="0.008"/>
  <testcase classname="extend.api.CreateReport" name="extend" time="0.269"/>
  <testcase classname="testsuite2.test.EntityType_PUT_with_indistinct" name="Update_EntityType" time="25.623">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
at auth.api.VerifyStatusLine.ensureLine200(VerifyStatusLine.java:22)
at depend_1.api.FrameSuite.EntityType_PUT_Update(FrameSuite.java:4570)
at main.api.ExecuteAPILead.Put(ExecuteAPILead.java:181)
at apache.api.Shuffle.globalAdmin(Shuffle.java:70)
at apache.api.Operation.worksheet(Operation.java:13)
at testsuite2.test.EntityType_PUT_with_indistinct.Update_EntityType(EntityType_PUT_with_indistinct.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Update_EntityType -->
</testsuite> <!-- Test -->
